### ISSUE TITLE
Slowness due to json-to-ast parsing

### ISSUE THREAD

**Issue by torifat** [atlassian/better-ajv-errors#51]
Check https://github.com/stoplightio/spectral/issues/455 for more info.
> The potential solution would be to swap `json-to-ast` parser used in `better-ajv-errors` with our alternate version of `jsonc-parser`.

**Comment by philsturgeon** [comment]
This would be awesome!

**Comment by torifat** [comment]
@philsturgeon It would be really cool if I could get some example of those "certain circumstances" :)
