### ISSUE TITLE
Drop support for node < 8

### ISSUE THREAD

**Issue by ext** [atlassian/better-ajv-errors#69]
This package has runtime dependencies on both `@babel/runtime` and `core-js` due to the legacy build needed for ancient unmaintained node versions. Node 8 ends it support at 2019-12-31 and to me it makes little sense to support even older versions.

To me this is an issue because it pulls those packages as a indirect dependency for my library which has absolutely no need for it and I'd like to keep the amount of dependencies as low as possible.

If you agree with this I would gladly write a PR myself.

**Comment by ext** [comment]
For anyone else interested in this I've forked the project and published as [@sidvind/better-ajv-errors](https://www.npmjs.com/package/@sidvind/better-ajv-errors) until #70 is merged (or declined). However, my intention isn't to maintain a fork so use with caution.

**Comment by torifat** [comment]
Yeah, it's probably make sense to drop any version older than 8 at this point. But, why is that a problem for you if you using a newer version of node? In frontend, you can have bundle size issues but I suppose this package is not for frontend usage.

**Comment by ext** [comment]
I agree it is not for frontend usage which is why it makes little sense to me to depend on `@babel/runtime` and `core-js`.

If anyone need to run this in frontend it would probably be better and more flexible for them to transpile and include relevant polyfills themselves.

**Comment by torifat** [comment]
Dropping support should be breaking change so I will introduce this in the next major version. Thanks.

**Comment by ext** [comment]
Any progress with this? Node 8 has been EOL for quite a while now and node 10 is up next in half a year (2021-04-30).

**Comment by torifat** [comment]
Closed via #101
