### ISSUE TITLE
Export ES6 modules

### ISSUE THREAD

**Issue by dtieber** [atlassian/better-ajv-errors#75]
This is actually not an issue, but a feature request: 
Currently, you're exporting CJS modules plus Typescript's specific "export equals" syntax in the type definition. You're shipping two flavors (`legacy` and `modern`) already, but babel turns your ES6 exports (in `./src`) to CJS exports in `./dist/modern`.  Otherwise, I'd suggest adding a note to the Readme that you'd need to activate the `esModuleInterop` Typescript flag. 

I'm happy to contribute a PR if you want.

**Comment by torifat** [comment]
Closed via #101 

I will take care of the `typescript` issue in a separate PR.
