### ISSUE TITLE
"split of undefined" at import

### ISSUE THREAD

**Issue by fxi** [atlassian/better-ajv-errors#87]
Hello,

I got a "split of undefined" at import, without doing anything else, locally (snowpack) and on codesandbox (parcel):

Reproducible here :
https://codesandbox.io/s/flamboyant-star-j26ye?file=/src/index.js

Works ( removed better-ajv-errors )
```js
import "./styles.css";
import Ajv from 'ajv';
// import betterAjvErrors from 'better-ajv-errors';
const ajv = new Ajv({ jsonPointers: true });
const validate = ajv.compile({type:'number'});
const valid = validate(2);
document.getElementById("app").innerHTML = `
 N errors : ${ valid?0:valid.errors.length}
`;
```

Does not work
```js
import "./styles.css";
import Ajv from 'ajv';
import betterAjvErrors from 'better-ajv-errors';
const ajv = new Ajv({ jsonPointers: true });
const validate = ajv.compile({type:'number'});
const valid = validate(2);
document.getElementById("app").innerHTML = `
 N errors : ${ valid?0:valid.errors.length}
`;
```

Error:
![image](https://user-images.githubusercontent.com/1196833/104007999-1810a900-51a9-11eb-9a90-3d7aed0119f1.png)

Have a nice day !

**Comment by pyros2097** [comment]
@fxi it seems this library only works in nodejs environment. It has a few deps that work only in nodejs.
https://github.com/atlassian/better-ajv-errors/blob/master/index.js#L4

**Comment by fxi** [comment]
@pyros2097 Was that on the fourth line of `index.js` ? I did not even went that far. haha.
I wrongly guessed that using format : 'js' would work in the browser.
Thanks
