### ISSUE TITLE
Issue:- process is not defined

### ISSUE THREAD

**Issue by akshayraina-github** [atlassian/better-ajv-errors#96]
Hello Team.
Please help

1st issue
TS Error
Object literal may only specify known properties, and 'jsonPointers' does not exist in type 'Options'

2nd issue
ReferenceError: process is not defined
    at eval (index.js?9eb4:8)
    at ./node_modules/@babel/highlight/node_modules/chalk/index.js (main.js:74)

Code:-
import betterAjvErrors from '@sidvind/better-ajv-errors';
const ajv = new Ajv({ jsonPointers: true });
const validate = ajv.compile(schema);
validate(schemaObject);
const errors = validate.errors;
console.log('better errors', betterAjvErrors(schema, schemaObject, errors));

**Comment by torifat** [comment]
It looks like an issue with your build. Not related to this package.
